name: CloudFront Cache Invalidation

on:
  push:
    branches:
      - main

jobs:
  invalidate_cache:
    runs-on: ubuntu-latest
    steps:
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create Cache Invalidation
        id: invalidate
        run: |
          invalidation_id=$(date +%s)
          aws cloudfront create-invalidation --distribution-id EHJ7UGRPNEPWU --paths "/*" --caller-reference "${invalidation_id}"

