- name: Invalidate CloudFront cache
  run: |
    aws cloudfront create-invalidation --distribution-id EHJ7UGRPNEPWU --paths "/*"
  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
